### PR TITLE
Only admins can place shapes

### LINKED ISSUE #16: Allowing the Administrator to Modify Shapes
As an administrator, I can modify the shapes being rendered

# Tasks:
 - As an administrator, I can add shapes to the rendering area
- As an administrator, I can remove shapes from the rendering area
- As an administrator, I can click and drag shapes around the rendering area
NOTE: any text accompanying the shape moves with the shape

# Tests:
 - Verify that the administrator can add, move, and remove shapes
- Verify that guest users cannot perform any of these functions

**Priority:** High

### PR DESCRIPTION
**Pull request by typokign**
Closes #16

### CODE REVIEW

**Review by jt8483 — APPROVED** [review]

**Comment by AAE1997** [comment]
Why was I removed from the group? I just got an email saying I have been removed from the @B- Programmers organization. Is this incorrect?

**Comment by typokign** [comment]
The project is over, there are no more tasks to complete.

**Comment by AAE1997** [comment]
Am I the only one getting this message or is everyone else getting the same message?

**Comment by typokign** [comment]
We're archiving the project now that it has been completed and submitted. Those of us who contributed code to the repository are displaying it on our profiles as part of our portfolio.

**Pull request merged**
